config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    resources :application_permissions, only: :index, shallow: true do
      patch :assign, param: :user_id, on: :collection
    end
  end

  resources :movie_countries

  resources :movies do
    resources :movie_thumbnails
    collection do
      get "title_search"
    end
  end
  resources :tv_programs do
    get :comments, :index, to: "comments#index"
  end
  get "tv_programs/:year/:month", to: "tv_programs#index"

  resources :directors
  resources :countries
  resources :actors
  resources :users do
    resource :user_setting, only: [:show] do
      patch :application_editor_permission
    end
  end

  resources :watched_tv_programs
  resources :watched_movies
  resources :recordeds

  get "auth/google/callback", to: "omniauth_callbacks#google_callback"
  get "auth/twitter/callback", to: "omniauth_callbacks#twitter_callback"
  get "auth/github/callback", to: "omniauth_callbacks#github_callback"
  get "auth/facebook/callback", to: "omniauth_callbacks#facebook_callback"
  get "auth/failure" => "sessions#failure"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "login_mobile" => "sessions#login_mobile"

  root to: "tv_programs#index"
end

app/views/calendar/_calendar.html.slim
= month_calendar start_date: @start_date, events: programs do |date, programs|
  = date.mday

  - if policy(TvProgram.new).new?
    = link_to "new", new_tv_program_path(date: date)

  - programs.each do |program|
    div
      = link_to program.movie.title_ja, movie_path(program.movie)
      a.glyphicon.glyphicon-list-alt href="#staticModal#{program.id}" data-toggle="modal"

      div.modal[id="staticModal#{program.id}" tabindex="-1" role="dialog" aria-labelledby="staticModalLabel" aria-hidden="true" data-show="true" data-keyboard="false" data-backdrop="static"]
        .modal-dialog
          .modal-content
            .modal-header
              button.close[type="button" data-dismiss="modal"]
                span[aria-hidden="true"] ×
                span.sr-only 閉じる
              h4.modal-title
                = link_to "#{program.movie.title_ja} (#{program.movie.title})", movie_path(program.movie)
            .modal-body
              div
                - program.movie.thumbnails.each do |thumbnail|
                  = image_tag thumbnail.image.url, style: "width: 130px; height: 200px; margin-right: 3px;"
              table.table.table-condensed
                tr
                  td 開始
                  td = program.on_air_start.to_s(:datetime_ja)
                tr
                  td 終了
                  td = program.on_air_end.to_s(:datetime_ja)
                tr
                  td コメント数
                  td = program.comments.count
                - if policy(program).edit?
                  tr
                    td id
                    td = program.id
                  tr
                    td movie_id
                    td = program.movie.id
                  tr
                    td edit
                    td = link_to "edit", edit_tv_program_path(program)
                  tr
                    td delete
                    td = link_to "delete", tv_program_path(program), method: :delete, confirm: "削除しますか?"
            .modal-footer
              button.btn.btn-default[type="button" data-dismiss="modal"] 閉じる
    - if user
      .button_group
        - watched = user.watched_tv_programs.find_or_initialize_by(tv_program_id: program.id)
        .watched_tv_button> id="watched_tv_#{watched.tv_program_id}" 
          = render "watched/watched_toggle", watched: watched, user: @current_user
        - rec = user.recordeds.find_by(tv_program_id: program.id)
        .remove_tv_button> id="recorded_#{rec.tv_program_id}" 
          = render "recordeds/recorded_toggle", recorded: rec, user: @current_user
    = link_to "実況リプレイ",  tv_program_comments_path(program)