config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    resources :application_permissions, only: :index, shallow: true do
      patch :assign, param: :user_id, on: :collection
    end
  end

  resources :movie_countries

  resources :movies do
    resources :movie_thumbnails
    collection do
      get "title_search"
    end
  end
  resources :tv_programs do
    get :comments, :index, to: "comments#index"
  end
  get "tv_programs/:year/:month", to: "tv_programs#index"

  resources :directors
  resources :countries
  resources :actors
  resources :users do
    resource :user_setting, only: [:show] do
      patch :application_editor_permission
    end
  end

  resources :watched_tv_programs
  resources :watched_movies
  resources :recordeds

  get "auth/google/callback", to: "omniauth_callbacks#google_callback"
  get "auth/twitter/callback", to: "omniauth_callbacks#twitter_callback"
  get "auth/github/callback", to: "omniauth_callbacks#github_callback"
  get "auth/facebook/callback", to: "omniauth_callbacks#facebook_callback"
  get "auth/failure" => "sessions#failure"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "login_mobile" => "sessions#login_mobile"

  root to: "tv_programs#index"
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[show edit update destroy]
  after_action :verify_authorized

  def index
    @movies = Movie.includes(:director, :actors).order(:title_ja).all
    authorize @movies
    respond_to do |format|
      format.html 
      format.json {render json: @movies}
    end
  end

  def new
    @movie = Movie.new
    authorize @movie
  end

  def create
    @movie = Movie.new(movie_params)
    authorize @movie

    respond_to do |format|
      if @movie.save
        format.html do
          redirect_to @movie, notice: "Movie was successfully created."
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def show
    if @current_user
      @watched = @current_user.watched_movies
                              .find_or_initialize_by(movie_id: @movie.id)
    end
    authorize @movie
  end

  def edit
    @movie.thumbnails.build if @movie.thumbnails.count == 0
    authorize @movie
  end

  def update
    authorize @movie
    respond_to do |format|
      if @movie.update(movie_params)
        format.html do
          redirect_to @movie, notice: "saved"
        end
      else
        format.html do
          render :edit, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @movie
    @movie.destroy
    respond_to do |format|
      format.html do
        redirect_to movies_url, notice: "Movie was successfully destroyed."
      end
    end
  end

  def title_search
    @movies = Movie.where("title LIKE(?)", "%#{params[:keyword]}%")
    skip_authorization
    render json: @movies
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(
      :title, :title_ja,
      :director_id,
      :released_year, :released_country_id,
      :story,
      countries_attributes: [:id, :country_code, :_destroy]
    )
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.slim
.form-group[style="position: relative; height: 200px;"]
  - movie.thumbnails.each do |thumbnail|
    - if thumbnail.persisted? and thumbnail.image
      = image_tag thumbnail.image.url, style: "width: 150px; height: 200px; margin-right: 3px; float: left;" 
  - if movie.persisted?
    div[style="border: dashed 2px #0087f7; width: 150px; height: 200px; float: left;"]
      = form_tag(movie_movie_thumbnails_path(movie_id: movie.id), class: "dropzone", id: "upload-dropzone") do
        = hidden_field_tag("movie_thumbnail[movie_id]", movie.id)
        .fallback
          = file_field_tag("movie_thumbnail[image]")
br[clear="both"]
= form_for(movie) do |f|
  - if movie.errors.any?
    #error_explanation
      h2
        = pluralize(movie.errors.count, "error")
        |  prohibited this movie from being saved:
      ul
        - movie.errors.full_messages.each do |message|
          li
            = message
  - directors = Director.order(:name_ja).all.pluck(:name_ja, :id).sort!
  - countries = ISO3166::Country.all.map do |c| [c.translated_names.join(" "), c.number]; end
  .form-group
    label[for="editTitle"] 原題
    = f.text_field :title, id: "editTitle", class: "form-control", placeholder: "Back to the Future"
  .form-group
    label[for="editTitleJa"] 邦題
    = f.text_field :title_ja, id: "editTitleJa", class: "form-control", placeholder: "バック・トゥ・ザ・フューチャー"
  .form-group
    label[for="editDirector"] 監督
    = f.select :director_id, directors, {include_blank: true}, {id: "editDirector", class: "form-control"}
  .form-group
    label[for="editCountry"] 製作国
    - movie.countries.build
    = f.fields_for :countries do |f_country|
      = f_country.select :country_code, countries, {include_blank: true}, {id: "editCountry", class: "form-control"}
  .form-group
    label[for="editReleasedYear"] 公開年
    = f.text_field :released_year, id: "editReasedYear", class: "form-control", placeholder: "1985"
  .form-group
    label[for="editStory"] あらすじ
    = f.text_area :story, id: "editStory", class: "form-control", placeholder: "1985年のカリフォルニア州ヒルバレーに住むロックとペプシコーラが大好きな高校生マーティ・マクフライは、科学者である親友のエメット・ブラウン博士（通称ドク）を手伝って、深夜のショッピングモール「ツインパインズ・モール」の駐車場にて、スポーツタイプの乗用車デロリアンDMC-12を改造してドクが開発したタイムマシンの実験をする。"
  .form-group
    = f.submit class: "btn btn-primary"

app/views/movies/_movie.html.slim
.movie-thumbnails[style="width:320px; float:left; padding-left:15px;"]
  - if movie.thumbnails.count > 0
    - movie.thumbnails.each do |thumbnail|
      = image_tag thumbnail.image.url, class: "img-fluid", style: "width: 300px; height: 400px;"
  - else
      img.img-fluid[src="" width="300px" height="400px"]

.movie-info[style="float:left; padding-left:10px;"]
  - if user
    div[style="clear:both;"]
      - if policy(@movie).update?
        = link_to "edit", [:edit, @movie]
    br
    div id="watched_movie_#{movie.id}"
    = render "watched/watched_toggle",
            watched: user.watched_movies.find_or_initialize_by(movie_id: movie.id),
            user: user
  br
  table.table
    tr
      th 邦題
      td = movie.title_ja
    tr
      th 原題
      td = movie.title
    tr
      th 監督
      td = link_to movie.director.name_ja, movie.director
    tr
      th 公開
      td = movie.released_year
    tr
      th 製作国
      td
        - movie.countries.each do |country|
          = country.name
          br
    tr
      th 出演者
      td
        - movie.actors.each do |actor|
          = link_to actor.name_ja, actor
          br

app/views/movies/edit.html.slim
div[style="margin: 10px;"]
  = render "form", movie: @movie, user: @current_user

app/views/movies/index.html.slim
- if policy(@movies).edit?
  = link_to "new", new_movie_path
table.table
  thead
    tr
      th 邦題
      th 原題
      th 監督
      th 主演
      - if policy(@movies).destroy?
        th 操作
  tbody
    - @movies.each do |movie|
      tr
        td = link_to movie.title_ja, movie
        td = movie.title
        td = movie.director.name_ja if movie.director
        td = movie.actors.first.name_ja if movie.actors.count > 0
        - if policy(@movies).destroy?
          td = link_to "delete", movie_path(movie), method: :delete, confirm: "削除しますか?"

app/views/movies/new.html.slim
h1 New Movie
=<> link_to "add_director", new_director_path
||
=<> link_to "add_country", new_country_path
||
=<> link_to "add_actor", new_actor_path

.form[style="margin: 10px;"]
  = render 'form', movie: @movie
= link_to 'Back', movies_path

app/views/movies/show.html.slim
= render "movie", movie: @movie, user: @current_user