config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    resources :application_permissions, only: :index, shallow: true do
      patch :assign, param: :user_id, on: :collection
    end
  end

  resources :movie_countries

  resources :movies do
    resources :movie_thumbnails
    collection do
      get "title_search"
    end
  end
  resources :tv_programs do
    get :comments, :index, to: "comments#index"
  end
  get "tv_programs/:year/:month", to: "tv_programs#index"

  resources :directors
  resources :countries
  resources :actors
  resources :users do
    resource :user_setting, only: [:show] do
      patch :application_editor_permission
    end
  end

  resources :watched_tv_programs
  resources :watched_movies
  resources :recordeds

  get "auth/google/callback", to: "omniauth_callbacks#google_callback"
  get "auth/twitter/callback", to: "omniauth_callbacks#twitter_callback"
  get "auth/github/callback", to: "omniauth_callbacks#github_callback"
  get "auth/facebook/callback", to: "omniauth_callbacks#facebook_callback"
  get "auth/failure" => "sessions#failure"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "login_mobile" => "sessions#login_mobile"

  root to: "tv_programs#index"
end

app/models/movie_country.rb
class MovieCountry < ApplicationRecord
  belongs_to :movie
  validates :movie_id, uniqueness: {scope: [:country_code]}

  def name
    c = ISO3166::Country.find_country_by_number(self.country_code)
    return "" if c.nil?
    c.local_name
  end

  def self.create_from_task(movie, countries)
    AfrLoadCountries::Country.find_country_by_names(countries, delimiter: "◆").each do |country|
      movie.countries.find_or_create_by(country_code: country.number)
    end
  end
end

app/controllers/movie_countries_controller.rb
class MovieCountriesController < ApplicationController
  before_action :set_movie_country, only: [:show]
  after_action :verify_authorized

  # GET /movie_countries
  # GET /movie_countries.json
  def index
    @movie_countries = MovieCountry.select("country_code").distinct
    authorize @movie_countries
  end

  # GET /movie_countries/1
  # GET /movie_countries/1.json
  def show
    authorize @movie_country
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_country
      @movie_country = MovieCountry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_country_params
      params.require(:movie_country).permit(:movie_id, :country_code)
    end
end

app/helpers/movie_countries_helper.rb
module MovieCountriesHelper
end

app/views/movie_countries/_form.html.slim
= form_for(movie_country) do |f|
  - if movie_country.errors.any?
    #error_explanation
      h2
        = pluralize(movie_country.errors.count, "error")
        |  prohibited this movie_country from being saved:
      ul
        - movie_country.errors.full_messages.each do |message|
          li = message
  .actions
    = f.submit

app/views/movie_countries/edit.html.slim
h1
  | Editing Movie Country
= render 'form', movie_country: @movie_country
= link_to 'Show', @movie_country
|  | 
= link_to 'Back', movie_countries_path

app/views/movie_countries/index.html.slim
p#notice
  = notice
h1
  | Movie Countries
table
  thead
    tr
      th[colspan="3"]
  tbody
    - @movie_countries.each do |movie_country|
      tr
        td
          = link_to 'Show', movie_country
        td
          = link_to 'Edit', edit_movie_country_path(movie_country)
        td
          = link_to 'Destroy', movie_country, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Movie Country', new_movie_country_path

app/views/movie_countries/new.html.slim
h1
  | New Movie Country
= render 'form', movie_country: @movie_country
= link_to 'Back', movie_countries_path

app/views/movie_countries/show.html.slim
p#notice
  = notice
= link_to 'Edit', edit_movie_country_path(@movie_country)
|  | 
= link_to 'Back', movie_countries_path