config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    resources :application_permissions, only: :index, shallow: true do
      patch :assign, param: :user_id, on: :collection
    end
  end

  resources :movie_countries

  resources :movies do
    resources :movie_thumbnails
    collection do
      get "title_search"
    end
  end
  resources :tv_programs do
    get :comments, :index, to: "comments#index"
  end
  get "tv_programs/:year/:month", to: "tv_programs#index"

  resources :directors
  resources :countries
  resources :actors
  resources :users do
    resource :user_setting, only: [:show] do
      patch :application_editor_permission
    end
  end

  resources :watched_tv_programs
  resources :watched_movies
  resources :recordeds

  get "auth/google/callback", to: "omniauth_callbacks#google_callback"
  get "auth/twitter/callback", to: "omniauth_callbacks#twitter_callback"
  get "auth/github/callback", to: "omniauth_callbacks#github_callback"
  get "auth/facebook/callback", to: "omniauth_callbacks#facebook_callback"
  get "auth/failure" => "sessions#failure"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "login_mobile" => "sessions#login_mobile"

  root to: "tv_programs#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :watched_tv_programs
  has_many :watched_movies
  has_many :recordeds
  validates :name, presence: true, uniqueness: true,
                   format: { with: /\A[a-z0-9_-]+\z/i }
  has_one :social_profile, dependent: :destroy

  has_one :setting, class_name: "UserSetting", dependent: :destroy
  accepts_nested_attributes_for :setting

  belongs_to :role

  def self.auth(name)
    User.find_by(name: name)
  end

  def admin?
    return false if role.nil?
    role.name == "admin"
  end

  delegate :abilities, to: :role
end

app/controllers/users/application_permissions_controller.rb
module Users
  class ApplicationPermissionsController < ApplicationController
    before_action :set_user, only: %i[assign]
    after_action :verify_authorized

    def index
      @users = User.includes(:setting).where(user_settings: {apply_editor_permission: true})
      authorize @users
    end

    # patch /application_permissions/assign/:user_id
    def assign
      authorize @user
      respond_to do |format|
        if @user.update(assign_params)
          format.html  { redirect_to edit_user_path(@user), status: :ok }
        else
          format.html  { redirect_to edit_user_path(@user), status: :bad_request }
        end
      end
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def assign_params
      params.require(:user).permit(:role_id)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  after_action :verify_authorized

  def index
    @users = User.all
    authorize @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize @user
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params_on_create)
    authorize @user

    respond_to do |format|
      if @user.save
        format.html do
          redirect_to @user, notice: "User was successfully created."
        end
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json do
          render json: @user.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          redirect_to @user, notice: "User was successfully updated."
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json do
          render json: @user.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to users_url, notice: "User was successfully destroyed."
      end
    end
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.includes(:setting).find(params[:id])
    @user.setting ||= UserSetting.new
  end

  def user_params_on_create
    params.require(:user).permit(:name, :nickname, setting_attributes: %i[is_tweet is_post_on_facebook])
  end

  def user_params
    params.require(:user).permit(:nickname, setting_attributes: %i[is_tweet is_post_on_facebook])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
div[style="margin: 10px;"]
  - if user.errors.any?
    #error_explanation
      h2
        = pluralize(user.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - user.errors.full_messages.each do |message|
          li
            = message
  .form-group
    label[for="role"] role
    p#role
      = user.role.name
  = form_for(user.setting, url: application_editor_permission_user_user_setting_path(user)) do |f|
    .form-group
      label[for="editEMail"] e-mail
      = f.text_field :mail_address, id: "editEMail", class: "form-control"
    = f.hidden_field(:apply_editor_permission, value: (not user.setting.apply_editor_permission))
    .form-group
      = f.submit "編集者権限を申請する", class: "btn btn-primary", disabled: user.setting.apply_editor_permission
  hr
  = form_for(user) do |f|
    .form-group
      label[for="editName"] name
      = f.text_field :name, id: "editName", class: "form-control"
    .form-group
      label[for="editNickname"] nickname
      = f.text_field :nickname, id: "editNickname", class: "form-control"
    .form-group
      = f.fields_for :setting do |s|
        .checkbox-inline
          = s.check_box :is_tweet, {class: "checkbox"}
          = s.label :is_tweet, "watched tv時 tweetする"
        .checkbox-inline
          = s.check_box :is_post_on_facebook, {class: "checkbox"}
          = s.label :is_post_on_facebook, "watched tv時 facebookに投稿する"
    .form-group
      = f.submit class: "btn btn-primary"

app/views/users/edit.html.slim
h1 設定
= render 'form', user: @user

app/views/users/index.html.slim
p#notice
  = notice
h1 Users
= link_to "login", login_path
br
- if @current_user
  = link_to "logout", logout_path
  br
table
  thead
    tr
      th[colspan="3"]
  tbody
    - @users.each do |user|
      tr
        td = link_to user.nickname, user
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1
  | New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice
  = notice
= @user.name
= link_to 'Edit', edit_user_path(@user)
|  | 
= link_to 'Back', users_path